config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'profiles#index'
  resources :profile
  # get '/profile/:id', to: 'profiles#show'
  # post '/search', to: 'profiles#search'
  # post '/create', to: 'profiles#create'
  # get '/search?:value', to: 'profiles#search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  # validates :name, :url, presence: true
  # validates :url, uniqueness: true
  # validates :url, format: { with: /@.{1,}/}

  def self.search(search)
    if search
      profile = Profile.where('name LIKE ? OR username LIKE ? OR desc LIKE ?',
                              "%#{search}%", "%#{search}%", "%#{search}%")
      # Profile.find_by(name: search)
      where(id: profile) if profile
    else
      Profile.all
    end
  end

  # private
  #
  #   def process_xor_url
  #     unless charge.match()
  #       errors.add(:base, "Specify a charge or a payment, not both")
  #     end
  #   end
  # scope :verify, ->(id) {Profile.find(id)}
end

app/models/scraper.rb
# This module scraps a twitter profile, and gets its image, username
# and description. To use it, import the module, and call it.
# let 'url' be twitter.com/anything or https://twitter.com/anything.
# Scraper.scrape(url)
require 'httparty'
require 'nokogiri'
require 'byebug'
require 'shorturl'
require 'embiggen'

module Scraper
  def self.scrape(page_query)
    # expressions to check up
    start = 'https://'
    twitter = %r{twitter.com\/.{1,}}
    # constants to be scrapped
    img = 'img.ProfileAvatar-image'
    nick = 'h2.ProfileHeaderCard-screenname.u-inlineBlock.u-dir'
    desc = 'p.ProfileHeaderCard-bio.u-dir'

    # URL treatments
    url = ''
    url = start unless page_query.start_with?(start)
    url << page_query if page_query.match(twitter)
    url << "twitter.com/#{page_query[1..]}" if page_query.start_with?('@')
    if Embiggen::URI(page_query.to_s).shortened?
      url = Embiggen::URI(page_query.to_s).expand.to_s
    end
    # parsing and scraping
    unparsed_page = HTTParty.get(url)
    case unparsed_page.code
    when 404
      puts "error..."
      unparsed_page = HTTParty.get("https://twitter.com/unknown")
    when 500..600
      puts "error..."
      unparsed_page = HTTParty.get("https://twitter.com/unknown")
    end

    parsed_page = Nokogiri::HTML(unparsed_page)
    profile_pic = parsed_page.css(img).attribute('src')
    profile_nickname = parsed_page.css(nick)
    profile_desc = parsed_page.css(desc)

    # return a hash (dictionary) with profile info
    {
      img: ShortURL.shorten(profile_pic.to_s).to_s,
      username: profile_nickname.text.strip.gsub('\n', ''),
      url: ShortURL.shorten(url.to_s).to_s,
      desc: profile_desc.text.strip.to_s
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  include Scraper
  require 'json'
  def index
    @profiles = Profile.search(params[:search])
  end

  def new
    @profile = Profile.new
  end

  def create
    @values = Scraper.scrape(allowed_params[:url])
    @profile = Profile.create(name: allowed_params[:name],
                              image: @values[:img],
                              username: @values[:username],
                              url: @values[:url], desc: @values[:desc])
    @profile.save
    redirect_to root_path
    # byebug
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @values = Scraper.scrape(edit_params[:url])
    @profile = Profile.find(params[:id])
    @profile.update(name: edit_params[:name],
                    image: @values[:img], username: edit_params[:username],
                    url: @values[:url], desc: edit_params[:desc])

    redirect_to profile_path(@profile)
  end

  def destroy
    @profile = Profile.find(params[:id]).destroy
    redirect_to root_path
  end

  def search
    @profile = Profile.all
    render json: @profile
    # @fetched_profiles = Profile.find(:all).select {|p| p.username ==  }
  end

  private

  def search_params
    params.require(:profile).permit(:name, :username, :desc, :search)
  end

  def edit_params
    params.require(:profile).permit(:name, :url, :image, :username, :desc)
  end

  def allowed_params
    params.require(:profile).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FretadaoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_nav_bar.html.erb
<nav class="amber darken-1">
  <ul>
    <li><%= link_to "Home", root_path, class:"blue-text text-darken-2" %></li>
    <li><%= link_to "New profile", "/profiles/new", class:"blue-text text-darken-2" %></li>
  </ul>
</nav>

app/views/profiles/edit.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Edit page</title>
  </head>
  <body class="light-blue darken-1">
    <%= render "profiles/nav_bar" %>
    <h2 class="blue-text text-lighten-5">Edit existing profile</h2>
    <h4 class="blue-text text-lighten-4 center">Twitter Profile</h4>
      <div class="container row">
      <%= form_for @profile do |f| %>
        <div class="center">
          <img alt="Profile image" src="<%= @profile.image %>" class="responsive-img circle"/>
        </div>
        <br>
        <div class="col s6">
          <label class="left light-blue-text text-lighten-4">Name:</label>
          <%= f.text_field :name, class:"col s3 cyan-text text-lighten-4" %>
        </br>
        </div>

        <div class="col s6">
          <label class="left light-blue-text text-lighten-4">URL/@user:</label>
          <%= f.text_field :url, class:"col s3 cyan-text text-lighten-4" %>
        </br>
        </div>

        <div class="col s6">
          <label class="left light-blue-text text-lighten-4">Username:</label>
          <%= f.text_field :username, class:"col s3 cyan-text text-lighten-4" %>
        </br>
        </div>

        <div class="col s6">
          <label class="left light-blue-text text-lighten-4">Description:</label>
          <%= f.text_field :desc, class:"col s3 cyan-text text-lighten-4" %>
        </br>
        </div>


        <%= f.submit "Save", class:"btn waves-effect waves-light amber darken-3" %>
      </div>
    <% end %>

  </body>
</html>

app/views/profiles/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="events.js" type="javascript.js"></script>
    <title>Twitter Fetcher</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="light-blue darken-1">
    <%= render "profiles/nav_bar" %>
    <div class="row container">
    <h2 class="blue-text text-lighten-5">Twitter Fetcher</h2>
    <h5 class="blue-text text-lighten-4">Crawling in my rails, these tweets they will not heal!</h5>
      <%= form_tag(profiles_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search], placeholder:"Search", class:"col s3 cyan-text text-lighten-4") %>
        &nbsp; &nbsp;&nbsp;&nbsp;
        <button class="btn waves-effect waves-light amber darken-3" type="submit" name="commit"><i class="material-icons right">search</i>Search</button>        
      <% end %>
    </div>

    <!-- <form action="/search" method="POST">
      <label for="input">Search profile: <input type="text" name="search" placeholder="gameideamachine"/></label>
      <button type="submit" class="fetcher">Search profile</button>
    </form> -->
    <div class="container">
      <ul id="profiles" class="collection">
        <% @profiles.each do |profile| %>
          <li class="collection-item row light-blue lighten-3">
            <%= link_to profile.name, profile_path(profile), class:"collection-item col s6 light-blue lighten-3 center-align blue-text text-darken-2" %>
            <%= link_to "External link", profile.url, target: "_blank", class:"collection-item col s6 light-blue lighten-3 center-align blue-text text-darken-2" %>
          </li>
        <% end %>
      </ul>
    </div>




  </body>
</html>

app/views/profiles/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="light-blue darken-1">
    <%= render "profiles/nav_bar" %>
    <div class="container">
    <h2 class="blue-text text-lighten-5">Add new profile</h2>
    <%= form_for @profile do |f| %>
      <div class="col s6">
        <%= label_tag(:name, "Screenname:") %>
        <%= f.text_field :name, placeholder: "Fretadao",
        class:"col s3 cyan-text text-lighten-4" %></br>
      </div>
      <div class="col s6">
        <%= label_tag(:url, "URL/handler:") %>
        <%= f.text_field :url, placeholder: "@fretadao",
        class:"col s3 cyan-text text-lighten-4" %></br>
        <%= f.submit "Create" %>
      </div>
    <% end %>
    </div>

  </body>
</html>

app/views/profiles/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Mostrar usuario</title>
  </head>
  <body class="light-blue darken-1">
    <%= render "profiles/nav_bar" %>
    <div class="container">

      <div class="center">
        <img alt="Profile image" src="<%= @profile.image %>" class="responsive-img circle"/>
      </div>
      <br>
      <h2 class="cyan-text text-accent-2"><%= @profile.name %></h2>
      <br>
      <span class="amber-text text-lighten-2"><%= @profile.username %></span>
      <br>
      <a class="cyan-text text-accent-2" href="<%= @profile.url %>">perfil</a>
      <br>
      <p class="cyan-text text-accent-2"><span class="cyan-text text-lighten-3">Description: </span><%= @profile.desc %></p>
      <a href="/profiles/<%=@profile.id%>/edit"><button type="submit" class="btn waves-effect waves-light amber darken-3"><i class="material-icons right">edit</i>Edit</button></a> &nbsp; &nbsp;&nbsp;&nbsp;
      <%= link_to "delete", @profile, method: :delete, data: { confirm: "Deseja realmente excluir?" }, class:"red-text text-accent-2"%>
    </div>
  </body>
</html>